### ISSUE TITLE
readme `install_github()` typo?

### ISSUE THREAD

**Issue by zackarno** [nawendt/gribr#27]
Thanks for the package! I just got it installed and i believe i noted a typo in the readme installation instructions:

You've written

```
devtools::install_github("nawendt/gribr", configure.args="ECCODES_LIBS=-L/path/to/eccodes/lib ECCODES_CPPFLAGS=-I/path/to/eccodes/include")
```
when I think it should be (like in the `install.packages()` version):

```
devtools::install_github("nawendt/gribr",configure.args=c("ECCODES_LIBS=-L/path/to/eccodes/lib", "ECCODES_CPPFLAGS=-I/path/to/eccodes/include"))
````

**Comment by nawendt** [comment]
It turns out that it works both ways. Looking at the [documentation](https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/install.packages), it says about `configure.args`:

> If a character vector with no names is supplied, the elements are concatenated into a single string (separated by a space)...

The single string is essentially treated like a character vector with one element. All vectors will just get turned into a single string anyway. It's probably more "canonical" to use the character vector version, however. I'll think about changing it, but I don't think doing it either way will cause anyone any trouble.

**Comment by zackarno** [comment]
Nice i didn't realize it worked both ways. I thought that adjustment was the solution that the resolved the errors I was getting. But it must have been another slight adjustment I made to the code without properly tracking the sequence I was executing the code. Thanks for the reply anyways!
